import type { Metadata } from "next";
import "./globals.css";
import { newTitle, pencerio, dancingScript, anton, author } from "./fonts";
import AnimatedLayout from "@/components/AnimatedLayout";
import { CartProvider } from "@/components/CartSystem";
import Navbar from "@/components/Navbar";
import { auth } from "@/auth";
import Footer from "@/components/Footer";
import PreloaderWrapper from "@/components/PreloaderWrapper";

export const metadata: Metadata = {
  title: "Ilea Real ones only.",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth();

  return (
    <html lang="en"
    data-qb-installed="true"
    >
      <CartProvider>
        <body
          className={`${author.variable} ${newTitle.variable} ${pencerio.variable} ${dancingScript.variable} ${anton.variable} antialiased`}
        >
        {/* <PreloaderWrapper> */}
           <Navbar session={session}/>
          <AnimatedLayout>{children}</AnimatedLayout>
        <Footer/>
        {/* </PreloaderWrapper> */}

        </body>
        
      </CartProvider>

    </html>
  );
}
