// app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import { newTitle, pencerio, dancingScript, anton, author } from "./fonts";
import AnimatedLayout from "@/components/AnimatedLayout";
import Footer from "@/components/Footer";
import { CartProvider } from "@/components/CartSystem";
import Navbar from "@/components/Navbar";
import { auth } from "@/auth";

export const metadata: Metadata = {
  title: "Ilea Real ones only.",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  const session = await auth();

  return (
    <html lang="en">
      <CartProvider>
         <body
        className={`${author.variable} ${newTitle.variable} ${pencerio.variable} ${dancingScript.variable} ${anton.variable} antialiased`}
      >
        <Navbar session={session} />  
          <AnimatedLayout>{children}</AnimatedLayout>
             <Footer/>
      </body>

      </CartProvider>
     
    </html>
  );
}
