// app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import { newTitle, pencerio, dancingScript, anton, author } from "./fonts";
import AnimatedLayout from "@/components/AnimatedLayout";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Ilea Real ones only.",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${author.variable} ${newTitle.variable} ${pencerio.variable} ${dancingScript.variable} ${anton.variable} antialiased`}
      >
        <div className="bg-[#242424]">
          <AnimatedLayout>{children}</AnimatedLayout>
        </div>
             <Footer/>
      </body>
    </html>
  );
}
